services:
  medusa:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: samplestore
    ports:
      - "9000:9000"
    depends_on:
      - postgres

    environment:
      DATABASE_URL: postgres://postgres:supersecret@localhost:5432/medusa_db


  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: medusa_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: supersecret
    volumes:
      - pg_data:/var/lib/postgresql/data



volumes:
  pg_data:
    driver: local

