services:
  medusa:
    build: .
    ports:
      - "9000:9000"
    environment:
      DATABASE_URL: postgres://medusa_user:root1234@postgres:5432/medusa_db
      JWT_SECRET: supersecret
      COOKIE_SECRET: supersecret
      ADMIN_CORS: http://localhost:9000,http://localhost:7000
    depends_on:
      - postgres
    volumes:
      - ./uploads:/app/uploads
    restart: always

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: medusa_user
      POSTGRES_PASSWORD: root1234
      POSTGRES_DB: medusa_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

volumes:
  postgres_data:
