version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: medusa-postgres
    environment:
      POSTGRES_USER: medusa_yash
      POSTGRES_PASSWORD: root
      POSTGRES_DB: medusa_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - medusa-network
    ports:
      - "5432:5432"

  medusa:
    build: .
    container_name: medusa-server
    environment:
      DATABASE_TYPE: postgres
      DATABASE_URL: postgres://medusa_yash:root@postgres:5432/medusa_db
    depends_on:
      - postgres
    ports:
      - "9000:9000"
    networks:
      - medusa-network
    volumes:
      - .:/app

volumes:
  postgres_data:

networks:
  medusa-network:
