# Use the official Node.js image as the base image
FROM node:18

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy the package.json and package-lock.json files to the working directory
COPY package*.json ./

# Install the project dependencies
RUN npm install

# Install Medusa CLI globally
RUN npm install -g @medusajs/medusa-cli

# Copy the rest of the application code to the working directory
COPY . .

# Expose the port on which the Medusa server will run
EXPOSE 9000

# Start the Medusa server in development mode using the Medusa CLI
CMD ["medusa", "develop"]
